;             
CREATE USER IF NOT EXISTS "SA" SALT 'd92d35a23aa7f300' HASH '99b017f087492381ae9ec5eb50f990d7360a55fe75220960cae20c3977f23c2a' ADMIN;         
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_6A717B38_EE1F_4E96_9DF7_B1F5DFCC978E" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_AB065EBE_61A3_405B_A429_02A23AF1DC3E" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_928219F4_D8E1_4556_91C4_F13B70B10F8B" START WITH 33 BELONGS_TO_TABLE;               
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_8E82A2A6_AA2F_4200_AED4_2DCD8843E1BD" START WITH 1 BELONGS_TO_TABLE;
CREATE CACHED TABLE "PUBLIC"."ACCESO"(
    "ID" INTEGER DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_AB065EBE_61A3_405B_A429_02A23AF1DC3E" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_AB065EBE_61A3_405B_A429_02A23AF1DC3E",
    "FECHA" TIMESTAMP,
    "IP" VARCHAR(50),
    "NAVEGADOR" VARCHAR(255),
    "SISTEMA" VARCHAR(255),
    "ID_URL" INTEGER,
    "ID_USUARIO" INTEGER
);            
ALTER TABLE "PUBLIC"."ACCESO" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_7" PRIMARY KEY("ID");       
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ACCESO;  
CREATE CACHED TABLE "PUBLIC"."COMENTARIO"(
    "ID" INTEGER DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_6A717B38_EE1F_4E96_9DF7_B1F5DFCC978E" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_6A717B38_EE1F_4E96_9DF7_B1F5DFCC978E",
    "COMENTARIO" CLOB,
    "USERNAME" VARCHAR(50),
    "ID_USUARIO" INTEGER
);     
ALTER TABLE "PUBLIC"."COMENTARIO" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_B" PRIMARY KEY("ID");   
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.COMENTARIO;              
CREATE CACHED TABLE "PUBLIC"."URL"(
    "ID" INTEGER DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_8E82A2A6_AA2F_4200_AED4_2DCD8843E1BD" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_8E82A2A6_AA2F_4200_AED4_2DCD8843E1BD",
    "CANTIDAD" INTEGER,
    "CODE" VARCHAR(10),
    "FECHA" TIMESTAMP,
    "URL" CLOB,
    "ID_USUARIO" INTEGER
);      
ALTER TABLE "PUBLIC"."URL" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1" PRIMARY KEY("ID");          
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.URL;     
CREATE CACHED TABLE "PUBLIC"."USUARIO"(
    "ID" INTEGER DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_928219F4_D8E1_4556_91C4_F13B70B10F8B" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_928219F4_D8E1_4556_91C4_F13B70B10F8B",
    "ADMINISTRADOR" BOOLEAN,
    "EDAD" INTEGER,
    "EMAIL" VARCHAR(100),
    "LATITUD" VARCHAR(100),
    "LONGITUD" VARCHAR(100),
    "NOMBRE" VARCHAR(100),
    "PASSWORD" VARCHAR(50),
    "PERFIL" CLOB,
    "USERNAME" VARCHAR(50)
);     
ALTER TABLE "PUBLIC"."USUARIO" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" PRIMARY KEY("ID");      
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.USUARIO; 
INSERT INTO "PUBLIC"."USUARIO" VALUES
(1, FALSE, 0, 'anonimo@gmail.com', NULL, NULL, 'Anonimo', '1234', NULL, 'anonimo'),
(2, TRUE, 22, 'cristianbg011@gmail.com', NULL, NULL, 'Cristian', '1234', NULL, 'admin');          
ALTER TABLE "PUBLIC"."URL" ADD CONSTRAINT "PUBLIC"."FKIXXK0D01VJ66N5SHXO29183CX" FOREIGN KEY("ID_USUARIO") REFERENCES "PUBLIC"."USUARIO"("ID") NOCHECK;       
ALTER TABLE "PUBLIC"."ACCESO" ADD CONSTRAINT "PUBLIC"."FK8EDSD9SXEIQ4SSJWUO6DGNLQP" FOREIGN KEY("ID_URL") REFERENCES "PUBLIC"."URL"("ID") NOCHECK;            
ALTER TABLE "PUBLIC"."ACCESO" ADD CONSTRAINT "PUBLIC"."FKAMO5QMN4STG03U0B33Y9SJEEY" FOREIGN KEY("ID_USUARIO") REFERENCES "PUBLIC"."USUARIO"("ID") NOCHECK;    
ALTER TABLE "PUBLIC"."COMENTARIO" ADD CONSTRAINT "PUBLIC"."FKGDCH5NDUO8BO4QBDYCSRSR4TN" FOREIGN KEY("ID_USUARIO") REFERENCES "PUBLIC"."USUARIO"("ID") NOCHECK;
